import { Channel, Category, Language, ChannelStatus } from './types';

export const MOCK_CHANNELS: Channel[] = [
  {
    id: '1',
    name: 'Crypto Whale Alerts',
    username: 'whale_alert',
    description: 'Real-time tracking of large cryptocurrency transactions. Be the first to know when whales move their funds.',
    members: 2450000,
    category: Category.CRYPTO,
    language: Language.ENGLISH,
    lastActive: '2 mins ago',
    avatarUrl: 'https://picsum.photos/seed/crypto1/200',
    verified: true,
    status: ChannelStatus.ACTIVE
  },
  {
    id: '2',
    name: 'TechCrunch News',
    username: 'techcrunch',
    description: 'Top technology news, startup breakdowns, and gadget reviews delivered daily.',
    members: 890000,
    category: Category.TECH,
    language: Language.ENGLISH,
    lastActive: '1 hour ago',
    avatarUrl: 'https://picsum.photos/seed/tech1/200',
    verified: true,
    status: ChannelStatus.ACTIVE
  },
  {
    id: '3',
    name: 'Daily Yoga Tips',
    username: 'daily_yoga',
    description: 'Your daily dose of mindfulness, yoga poses, and meditation techniques for a healthier life.',
    members: 120000,
    category: Category.FITNESS,
    language: Language.ENGLISH,
    lastActive: '5 hours ago',
    avatarUrl: 'https://picsum.photos/seed/yoga/200',
    status: ChannelStatus.ACTIVE
  },
  {
    id: '4',
    name: 'Cinephile Hub',
    username: 'movies_hub_official',
    description: 'Latest movie trailers, reviews, and behind-the-scenes content from Hollywood and beyond.',
    members: 450000,
    category: Category.MOVIES,
    language: Language.ENGLISH,
    lastActive: '12 hours ago',
    avatarUrl: 'https://picsum.photos/seed/movie1/200',
    status: ChannelStatus.ACTIVE
  },
  {
    id: '5',
    name: 'Global Breaking News',
    username: 'breaking_news_global',
    description: 'Unbiased breaking news from around the world as it happens. Politics, economy, and more.',
    members: 1200000,
    category: Category.NEWS,
    language: Language.ENGLISH,
    lastActive: '10 mins ago',
    avatarUrl: 'https://picsum.photos/seed/news1/200',
    verified: true,
    status: ChannelStatus.ACTIVE
  },
  {
    id: '6',
    name: 'JavaScript Mastery',
    username: 'js_mastery',
    description: 'Tutorials, tips, and tricks for modern JavaScript development. React, Node.js, and more.',
    members: 320000,
    category: Category.TECH,
    language: Language.ENGLISH,
    lastActive: '1 day ago',
    avatarUrl: 'https://picsum.photos/seed/js/200',
    status: ChannelStatus.ACTIVE
  },
  {
    id: '7',
    name: 'Noticias en Español',
    username: 'noticias_es',
    description: 'Las últimas noticias de España y América Latina. Actualizaciones minuto a minuto.',
    members: 670000,
    category: Category.NEWS,
    language: Language.SPANISH,
    lastActive: '30 mins ago',
    avatarUrl: 'https://picsum.photos/seed/spanish1/200',
    status: ChannelStatus.ACTIVE
  },
  {
    id: '8',
    name: 'Bitcoin Trading Signals',
    username: 'btc_signals_vip',
    description: 'High accuracy trading signals for BTC and ETH. Technical analysis and market updates.',
    members: 150000,
    category: Category.CRYPTO,
    language: Language.ENGLISH,
    lastActive: '3 hours ago',
    avatarUrl: 'https://picsum.photos/seed/btc/200',
    status: ChannelStatus.ACTIVE
  },
  {
    id: '9',
    name: 'Learn Python',
    username: 'learn_python_easy',
    description: 'From zero to hero in Python. Code snippets, libraries, and best practices.',
    members: 550000,
    category: Category.EDUCATION,
    language: Language.ENGLISH,
    lastActive: '2 days ago',
    avatarUrl: 'https://picsum.photos/seed/python/200',
    status: ChannelStatus.ACTIVE
  },
  {
    id: '10',
    name: 'Humor Negro',
    username: 'dark_humor_es',
    description: 'Los mejores memes y chistes en español. Solo para gente con sentido del humor.',
    members: 230000,
    category: Category.HUMOR,
    language: Language.SPANISH,
    lastActive: '4 hours ago',
    avatarUrl: 'https://picsum.photos/seed/meme1/200',
    status: ChannelStatus.ACTIVE
  },
  {
    id: '11',
    name: 'Wall Street Gems',
    username: 'wallstreetgems',
    description: 'Stock market insights, IPO analysis, and dividend investing strategies.',
    members: 780000,
    category: Category.FINANCE,
    language: Language.ENGLISH,
    lastActive: '45 mins ago',
    avatarUrl: 'https://picsum.photos/seed/finance/200',
    verified: true,
    status: ChannelStatus.ACTIVE
  },
  {
    id: '12',
    name: 'Gym Motivation',
    username: 'beast_mode_gym',
    description: 'Daily workout routines, diet plans, and motivational quotes to keep you moving.',
    members: 410000,
    category: Category.FITNESS,
    language: Language.ENGLISH,
    lastActive: '6 hours ago',
    avatarUrl: 'https://picsum.photos/seed/gym/200',
    status: ChannelStatus.ACTIVE
  },
  {
    id: '13',
    name: 'Arte Digital',
    username: 'digital_art_gallery',
    description: 'Showcasing the best digital art from artists around the world. Inspiration daily.',
    members: 180000,
    category: Category.ART,
    language: Language.SPANISH,
    lastActive: '1 day ago',
    avatarUrl: 'https://picsum.photos/seed/art/200',
    status: ChannelStatus.ACTIVE
  },
  {
    id: '14',
    name: 'History Facts',
    username: 'history_daily',
    description: 'Fascinating historical facts, rare photos, and "on this day" events.',
    members: 1100000,
    category: Category.EDUCATION,
    language: Language.ENGLISH,
    lastActive: '3 hours ago',
    avatarUrl: 'https://picsum.photos/seed/history/200',
    status: ChannelStatus.ACTIVE
  },
  {
    id: '15',
    name: 'Marvel vs DC',
    username: 'superheroes_fan',
    description: 'Discussions, polls, and news about the superhero cinematic universes.',
    members: 290000,
    category: Category.MOVIES,
    language: Language.ENGLISH,
    lastActive: '20 mins ago',
    avatarUrl: 'https://picsum.photos/seed/marvel/200',
    status: ChannelStatus.ACTIVE
  },
  {
    id: '16',
    name: 'Science Today',
    username: 'sci_today',
    description: 'Breakthroughs in physics, biology, and astronomy explained simply.',
    members: 620000,
    category: Category.EDUCATION,
    language: Language.ENGLISH,
    lastActive: '1 day ago',
    avatarUrl: 'https://picsum.photos/seed/science/200',
    verified: true,
    status: ChannelStatus.ACTIVE
  },
  {
    id: '17',
    name: 'Bollywood Masala',
    username: 'bollywood_news_hindi',
    description: 'All the gossip and news from the world of Bollywood in Hindi.',
    members: 950000,
    category: Category.MOVIES,
    language: Language.HINDI,
    lastActive: '10 mins ago',
    avatarUrl: 'https://picsum.photos/seed/bollywood/200',
    status: ChannelStatus.ACTIVE
  },
  {
    id: '18',
    name: 'DeFi Pulse',
    username: 'defi_pulse_news',
    description: 'Decentralized Finance news, yield farming opportunities, and protocol updates.',
    members: 130000,
    category: Category.CRYPTO,
    language: Language.ENGLISH,
    lastActive: '2 hours ago',
    avatarUrl: 'https://picsum.photos/seed/defi/200',
    status: ChannelStatus.ACTIVE
  },
  {
    id: '19',
    name: 'German Tech Review',
    username: 'technik_de',
    description: 'Technologie-News und Reviews auf Deutsch.',
    members: 85000,
    category: Category.TECH,
    language: Language.GERMAN,
    lastActive: '5 hours ago',
    avatarUrl: 'https://picsum.photos/seed/german/200',
    status: ChannelStatus.ACTIVE
  },
  {
    id: '20',
    name: 'Russian Markets',
    username: 'ru_markets',
    description: 'Financial news and market analysis for the Russian economy.',
    members: 310000,
    category: Category.FINANCE,
    language: Language.RUSSIAN,
    lastActive: '30 mins ago',
    avatarUrl: 'https://picsum.photos/seed/russian/200',
    status: ChannelStatus.ACTIVE
  },
  {
    id: '21',
    name: 'Pirate Bay (Proxy)',
    username: 'tpb_proxy_official',
    description: 'This channel is unavailable due to copyright infringement.',
    members: 0,
    category: Category.TECH,
    language: Language.ENGLISH,
    lastActive: '1 year ago',
    avatarUrl: 'https://ui-avatars.com/api/?name=PB&background=000&color=fff',
    status: ChannelStatus.BANNED
  }
];